# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Variable": "00_core.ipynb",
         "Function": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dezero.gjx.me/"

git_url = "https://github.com/JunxinGao/dezero/tree/master/"

def custom_doc_links(name): return None
