# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['Variable', 'Function']

# Cell
from .imports import *

# Cell
class Variable():
    def __init__(self, data):
        self.data = data

# Cell
class Function():
    def __call__(self, input:Variable):
        x = input.data
        y = self.forward(x)
        output = Variable(y)
        return output

    def forward(self, x):
        raise NotImplementedError()
